### ISSUE TITLE
Support for 7.0 MAT files

### ISSUE THREAD

**Issue by ncnc** [simonster/MAT.jl#37]
Apart from the currently supported 5.0 and 7.3 file formats, there is a 7.0 format, which is also appears to be based on HDF5. See e.g. http://www.mathworks.com/help/matlab/import_export/mat-file-versions.html

I tried reading a 7.0 file (containing a structure with a matrix field) and that file could be read with the same low-level code as 7.3., i.e. the patch below seemed to work correctly:
```
diff --git a/src/MAT.jl b/src/MAT.jl
index 8858610..b1d5876 100644
--- a/src/MAT.jl
+++ b/src/MAT.jl
@@ -49,6 +49,7 @@ function matopen(filename::String, rd::Bool, wr::Bool, cr::Bool, tr::Bool, ff::B
 
     # Send to appropriate module
     magic == "MATLAB 7.3 MAT-file".data ? MAT_HDF5.matopen(filename, rd, wr, cr, tr, ff) :
+    magic == "MATLAB 7.0 MAT-file".data ? MAT_HDF5.matopen(filename, rd, wr, cr, tr, ff) :
     magic == "MATLAB 5.0 MAT-file".data ? MAT_v5.matopen(filename, rd, wr, cr, tr, ff) :
         error("\"$filename\" is not a MAT file, or is an unsupported (v4) MAT file")
 end
```

**Comment by simonster** [comment]
`save -v7 ...` saves a file with header `"MATLAB 5.0 MAT-file"` that's essentially in MATLAB v5 format with compression, which we support and have [test data for](https://github.com/simonster/MAT.jl/tree/master/test/v7). I've never seen MATLAB write a file with the header `"MATLAB 7.0 MAT-file"`. Do you know what version of MATLAB you used and what parameters (if any) you passed to `save`?

**Comment by ncnc** [comment]
At least version `7.5.0` saves "MATLAB 7.0 MAT-file", when using `save
-v7.3`.

**Comment by ncnc** [comment]
I also tested with `7.12.0` and there I was only able to generate `5.0` and `7.3` files, so apparently they switched version numbers somewhere between 2007 and 2011. I also tried putting whitespace in the whole first `0x7c` bytes, and Matlab was still able to read the file so the beginning is really only a very regular comment field.

**Comment by simonster** [comment]
Thanks. I updated the file format detection based on my understanding of [the specification](http://www.mathworks.com/help/pdf_doc/matlab/matfile_format.pdf), which suggests that MATLAB checks that the first 4 bytes are non-zero and then looks at the version/endianness in 124-128.

**Comment by ncnc** [comment]
Thanks. I tested with master and it seems to work for my files.
