### ISSUE TITLE
Int64 problem in 'matread'

### ISSUE THREAD

**Issue by fsobral** [simonster/MAT.jl#41]
I'm using julia version 0.4.0-dev+4219 and have just updated MAT by Pkg.update().
When loading file [scsd8.mat](https://www.dropbox.com/s/uaenbgpxmv027iu/scsd8.mat.gz?dl=0) with the `matread("scsd8.mat")` command the following error occurs:

    julia> vars=matread("scsd8.mat")
    ERROR: MethodError: `skip_padding` has no method matching skip_padding(::IOStream, ::Int32,   ::Int32)
    Closest candidates are:
      skip_padding(::IO, ::Int64, ::Int32)
     in read_element at /home/fsobral/.julia/MAT/src/MAT_v5.jl:109
     in read_matrix at /home/fsobral/.julia/MAT/src/MAT_v5.jl:310
     in read at /home/fsobral/.julia/MAT/src/MAT_v5.jl:346
     in matread at /home/fsobral/.julia/MAT/src/MAT.jl:109

To solve this problem I've changed `Int` to `Int64` in lines 98 and 101 of file __MAT_v5.jl__.

**Comment by simonster** [comment]
I assume you have 32-bit Julia? If so, can you run `Pkg.checkout("MAT")` and try again?

**Comment by fsobral** [comment]
Yes, I have 32-bit Julia. I removed the .julia/MAT directory, but now I'm unable to Pkg.add("MAT") again (Pkg.checkout("MAT") did not work). I'll try later.

**Comment by fsobral** [comment]
Ok. My fault. I've run `Pkg.checkout("MAT")` and everything worked! Thanks.

**Comment by simonster** [comment]
Great, thanks.
