### ISSUE TITLE
HDF5 not properly installed

### ISSUE THREAD

**Issue by meaningofshape** [simonster/MAT.jl#44]
I am having trouble with 'using MAT'.  I get the error message 'HDF5 not properly installed

**Comment by vchuravy** [comment]
The right place for this issue is probably https://github.com/timholy/HDF5.jl

What does `Pkg.build("HDF5") give you?

**Comment by timholy** [comment]
https://github.com/timholy/HDF5.jl/issues/245

**Comment by meaningofshape** [comment]
My new message when 'using MAT': 
HDF5 File not defined while loading C:\...\.julia\v0.3\MAT\src\MAT_HDF5.jl, in expression starting on line 35
![image](https://cloud.githubusercontent.com/assets/10761087/8856100/c18e4e4a-3136-11e5-8f42-c1bb553a19f6.png)

Warning: replacing module MAT_HDF5
Warning: could not import HDF5.exists into MAT_HDF5
Warning: could not import HDF5.HDF5ReferenceObj into MAT_HDF5
Warning: could not import HDF5.HDF5BitsKind into MAT_HDF5

Also, thank you for your help and your work on these packages.  My current project is actually to translate some of our group's work into Julia packages, and your early contributions are what makes it (hopefully) possible.
