### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by laurentheirendt** [simonster/MAT.jl#66]
@simonster and @yuyichao ,

May you tag a new version of `MAT.jl`? Our `COBRA.jl` package is dependent on `MAT.jl` (great package by the way!), but in order to ensure the compatibility of `COBRA.jl` with `julia v0.6`, we need the latest fixes on `master`.

Thanks.

cc: @syarra

**Comment by laurentheirendt** [comment]
@simonster or @yuyichao ,

would you mind tagging the new version so that the new fix for `v0.6` is taken into account?

Thank you.

**Comment by bjarthur** [comment]
there are still a couple easy dep warns for julia 0.6 that could be fixed before tagging MAT.jl.  i'd be happy to submit a PR, but i haven't had much luck in getting my PRs merged here in the past...  :(

**Comment by tkelman** [comment]
0.3.2 was tagged
